[build]
  publish = "dist" # The folder containing your built site (default for Eleventy is "dist")
  functions = "netlify/functions" # Path to your serverless functions folder

[dev]
  # Optional: Configure local dev server if you're using `netlify dev`
  command = "npx eleventy --serve"
  port = 8080 # Default port Eleventy serves on

# Optional: Redirects, if needed
[[redirects]]
  from = "/contact"
  to = "/contact.html"
  status = 200
